### ISSUE TITLE
Question: Indexing in Intellij IDEA

### ISSUE THREAD

**Issue by CaptMars** [anatawa12/ForgeGradle-example#12]
Is it possible to fix this?
![image](https://user-images.githubusercontent.com/65482582/203158875-d2a1cf59-d048-4892-a89e-83aa8f76f1ea.png)
The code works, but I would like the IDE to understand what I write and give me hints

**Comment by anatawa12** [comment]
Did you resync after running setup tasks?

**Comment by CaptMars** [comment]
I don't know why, but I just made same steps as first time, and it worked like I wanted. Sorry and Thank you!
