### ISSUE TITLE
Running setupDecompWorkspace yields an error in :makeStart

### ISSUE THREAD

**Issue by ThatMightyGuy** [anatawa12/ForgeGradle-example#14]
I am running the task via `gradlew.bat` with `openjdk8-redhat` and getting this error:
```
> Task :makeStart FAILED
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 6
[ant:javac] error: Source option 6 is no longer supported. Use 7 or later.
[ant:javac] error: Target option 6 is no longer supported. Use 7 or later.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':makeStart'.
```
I'm assuming it's trying to build for Java 6. Am I doing something wrong?

**Comment by ThatMightyGuy** [comment]
Downgrading Gradle to 5.6.4 as per the project's README and setting `org.gradle.java.home` in `gradle.properties` seems to have fixed the immediate issue, but that doesn't seem like a good fix.

**Comment by anatawa12** [comment]
Which versions of (other) jdks have you installed? I've not tested yet but I think it's because of other version of jdks you've installed.

**Comment by ThatMightyGuy** [comment]
I have 8 and 17 with 17 being on `PATH`, so I have set `JAVA_HOME` in `gradlew.bat`, but I should have done it in `gradle.properties`. Still, it seems to have picked it up. I can try upgrading back to 7.4.

**Comment by ThatMightyGuy** [comment]
Yes. It looks like Gradle picked up the JDK 8 set in the batch file, but `javac` was still picked from `PATH`. Doing it the correct way resolved the issue.
