### ISSUE TITLE
Not compatible to Gradle 7.x

### ISSUE THREAD

**Issue by Hye0Ngit** [anatawa12/ForgeGradle-example#9]
Gradle 7.x changed `maven` to `maven-publish`, so this project won't work.

**Comment by anatawa12** [comment]
Can you show me your error message? building is tested with 7.0, 7.3 (in ForgeGradle repository) and 7.4.2 (I've pushed gradle-7 branch, which only updated gradle.)

If you're talking about warning message in gradle 6, please try run with `--warning-mode all`. ForgeGradle will show you that with gradle 7, ForgeGradle will never apply maven plugin and the way to disable applying maven plugin on Gradle 6 or older.

That's my mistake that I've forgotten upgrading Gradle to 7.x. I'll upgrade Gradle of this repository soon.
